config/routes.rb
Rails.application.routes.draw do
  resources :todos

  root to: "todos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  extend Enumerize

  enumerize :color, :in => %w(red orange yellow	green	cyan blue purple pink)

  validates_length_of :name, minimum: 5
  validates_uniqueness_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all.order(completed: :asc)
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todos_url, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todos_url, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:name, :completed, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Todolist"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  = content_tag :body, data: {controller: controller.controller_path, action: action_name} do
    .navbar.navbar-default.navbar-static-top
      .container
        a.navbar-brand href="/"Todolist

    .container
      = bootstrap_flash
      = yield

      footer

app/views/todos/_form.html.slim
= simple_form_for @todo, :html => { :class => "form-horizontal" } do |f|
  = f.input :name
  = f.input :color
    .colors
      - Todo.color.options.each do |color|
        span.dot data-todo-color=color[1] style = "background-color: #{color[1]}" class = "#{@todo.color_value == color[1] ? 'chosen' : ''}"
         = icon('fas', 'check')
    = f.hidden_field :color
  .controls
    = f.button :submit, :class => 'btn-primary'
    '
    = link_to t('.cancel', :default => t("helpers.links.cancel")), todos_path, :class => 'btn btn-default'

app/views/todos/edit.html.slim
- model_class = Todo
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/todos/index.html.slim
- model_class = Todo
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
  .grid-controls
    a data-grid="tiles"
      = icon('fas', 'th')
    a data-grid="list"
      = icon('fas', 'th-list')
#wrapper.list
  - @todos.each do |todo|
    .item class = "#{todo.completed ? 'completed' : ''}" data-todo-id=todo.id
      .inner-item
        .todo-name= todo.name
        .todo-color
          span.dot style = "background-color: #{todo.color}"
            - unless todo.color
              = "-"
        .todo-completed= check_box_tag "completed", todo.completed, todo.completed, data: {"todo-completed": true, path: todo_path(todo)}
        .todo-actions
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_todo_path(todo), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), todo_path(todo), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
.controls
  = link_to t('.new', :default => t("helpers.links.new")), new_todo_path, :class => 'btn btn-primary'

app/views/todos/new.html.slim
- model_class = Todo
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/todos/show.html.slim
- model_class = Todo
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @todo.name
p
  strong= model_class.human_attribute_name(:completed) + ':'
  br
  = @todo.completed
p
  strong= model_class.human_attribute_name(:color) + ':'
  br
  = @todo.color

= link_to t('.back', :default => t("helpers.links.back")), todos_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_todo_path(@todo), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), todo_path(@todo), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'